/*
cc12.2: You are given the source to an application which crashes when 
        it is run. After running it ten times in a debugger, you find 
        it never crashes in the same place. The application is single
        threaded, and uses only the C standard library. What kind of
        programming errors could be causing this crash ? How would you
        test each one?

Some general causes of random crashes:
    1. Random Variable: Random number or variable that may not be 
       fixed for every execution of the program. e.g., user input, a 
       random number generated by the program.
    2. Uninitialized Variable: Uninitialized variable may take on 
       arbitrary values. 
    3. Memory Leak: The program may have run out of memory. Other 
       culprits are totally random for each run since it depends on 
       the number of processes running at that particular time. This 
       also includes heap overflow or corruption of data on the stack.
    4. External Dependencies: The program may depend on another
       application, machine, or resource. If there are multiple 
       dependencies, the program could crash at any point.

Some check approach:   
    1. Check the resource of loading a file.
    2. Close down all other applications on the system then run.
    3. Use another machine to run. 
    4. Use tools. e.g., use runtime tools to check uninitialized
       variables, use valgrind to check the memory leak.     





*/